### PR TITLE
handled chart method pundit authorization to fix bug

### LINKED ISSUE #35: Bug fix: Pundit Authorization refactor caused charts to be unreadable.

### PR DESCRIPTION
**Pull request by amandaag39**

### CODE REVIEW

File: app/policies/vital_policy.rb
Comment (jeeheezy) [inline app/policies/vital_policy.rb:1]: See same logic applied multiple times (i.e. record.user_id == user.id). For code clarity sake, might be worth refactoring this into a separate private method that's descriptive of why you are doing this and call that method as a check for the instances where you call record.user_id == user.id

File: app/controllers/vitals_controller.rb [hunk 1]
```diff
@@ -1,6 +1,6 @@
 class VitalsController < ApplicationController
   before_action :set_vital, only: %i[ show edit update destroy ]
-  before_action { authorize(@vital || Vital) }
+  before_action :authorize_resource, except: %i[chart]
```
Comment (jeeheezy) [inline app/controllers/vitals_controller.rb]: There's no real reason to create a separate method called authorize_resource if the sole purpose is to have an exception for the authorize. Instead I believe you can do something like 
```
before_action(except: [:chart]) { authorize(@vital || Vital) }
```
to specify the exception

File: app/controllers/vitals_controller.rb [hunk 2]
```diff
@@ -76,6 +77,11 @@ def chart
   end
 
   private
+
+    def authorize_resource
```
Comment (jeeheezy) [inline app/controllers/vitals_controller.rb]: See above comment on before_action of why I feel this method might not be necessary

File: app/controllers/vitals_controller.rb [hunk 3]
```diff
@@ -59,6 +59,7 @@ def destroy
   # For chart actions
   def chart
     @selected_vital = current_user.vitals.find_by(id: params[:vital_id])
+    authorize @selected_vital
```
Comment (jeeheezy) [inline app/controllers/vitals_controller.rb]: If there's no distinction between @selected_vital and @vital aside from what you decided to name the variable, you could just adopt the standard naming convention and use @vital in line 61 and change your html.erb to reference @vital instead of @selected_vital. Using @vital in the chart method would allow you to continue to use an all-inclusive before_action without needing to create an exception and calling a separate authorize here since all of them use the same policy.

Comment (amandaag39) [reply app/controllers/vitals_controller.rb]: Great feedback thank you. Changed routes to accommodate this refactor. Code is looking better I think 😃
